hide_cursor = true

image {
    monitor = eDP-1      , 1920x1080@60, 0x0      , 1
    path = ~/Pictures/wallpapers/CyberPunk.jpg
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    size = 160
    rounding = -1
    position = 0, 40
    halign = center
    valign = center
}
